# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1c6349d403678aaa97353ea9f0ecea4ef2109f713e512e4e2d990ab7d27a86976408ebca25edd3acb5ab886163e1601cce8db99adf83c046eaf9f8d20b025f3

test:
  secret_key_base: 562c134ee9a522718948db79442dd73ee0dd24c3638e6853983270cb865c5d968f01f9468eb67fb4a0868d9fa7fb3c982b6ce94b434f7229ac651de499135ee9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
